# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: |
          npm install
      - name: Build web-component
        run: |
          npx nx build web-component
          # create the bundles required for studio-web
          npx nx bundle web-component
      - name: Build
        run: |
          npx nx build studio-web --base-href=/pr-preview/pr-${{github.event.number}}/ --configuration=production
          npx nx build studio-web --base-href=/pr-preview/pr-${{github.event.number}}/ --configuration=production --localize=fr --deleteOutputPath=false
          npx nx build studio-web --base-href=/pr-preview/pr-${{github.event.number}}/ --configuration=production --localize=es --deleteOutputPath=false
      - name: Publish Deploy Preview 🛫
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist/packages/studio-web
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
